config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  resources :books, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully edited"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
  <p id="notice">
  <%= flash[:notice] %>
  </p>
<% end %>
<h2>Edting Book</h2>

<% if @book.errors.any? %>
  <div id="errors_explanation">
    <% if @book.errors.count == 1 %>
      <h2>
        <%= @book.errors.count %> error prohibited this book from being saved:
      </h2>
    <% elsif @book.errors.count == 2 %>
      <h2>
        <%= @book.errors.count %> errors prohibited this book from being saved:
      </h2>
    <% end %>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @book do |f| %>
  <div class="field">
    <label>Title</label>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <label>Body</label>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit "Update Book" %>
  </div>
<% end %>
<%= link_to "Show", @book %>
｜
<a class="back" href="/books">Back</a>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p id="notice">
  <%= flash[:notice] %>
  </p>
<% end %>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", book %></td>
          <td><%= link_to "Edit", edit_book_path(book) %></td>
          <td><%= link_to "Destroy", book, method: :delete, "data-confirm" => "Are you sure?" %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<h2>New book</h2>

<% if @book.errors.any? %>
  <div id="errors_explanation">
    <% if @book.errors.count == 1 %>
      <h2>
        <%= @book.errors.count %> error prohibited this book from being saved:
      </h2>
    <% elsif @book.errors.count == 2 %>
      <h2>
        <%= @book.errors.count %> errors prohibited this book from being saved:
      </h2>
    <% end %>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @book, url: "/books", method: :post do |f| %>
  <div class="field">
    <label for="book-title">Title</label>
     <%= f.text_field :title %>
  </div>

  <div class="field">
    <label for="book-body">Body</label>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit "Create Book" %>
  </div>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p id="notice">
  <%= flash[:notice] %>
  </p>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @book.title %>

</p>
<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path(@book.id) %>
｜
<a class="back" href="/books">Back</a>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>Bookers</strong>
  へ！
</h1>
<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>
  印象を共有し交換することができます
</p>
<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>